spring:
  datasource:
    url: jdbc:h2:mem:${spring.application.name};MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
  rabbitmq:
    host: rabbit
    port: 5672
    
security:
  oauth2:
    resource:
      user-info-uri: http://userauthentication:8095/user
    
management:
  contextPath: /manage
  
http:
  client:
    ssl:
      trust-store: shared/truststores/truststore.jks
      trust-store-password: changeit

eureka:
  instance:
    statusPageUrlPath: ${management.contextPath}/info
    healthCheckUrlPath: ${management.contextPath}/health
  client: 
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    healthcheck:
      enabled: true
    
flyway:
  validate-on-migrate: false
  table: SCHEMA_VERSION
  
hystrix.command.default.execution.isolation:
  strategy: SEMAPHORE
  thread.timeoutInMilliseconds: 10000