server:
  port: 8092
  
security:
  oauth2:
    client:
      clientId: peticionamento
      clientSecret: peticionamento
      accessTokenUri: http://userauthentication:8095/oauth/token
      grant-type: client_credentials
      scope: server