server:
  port: 8761

eureka:
  server:
    enable-self-preservation: false
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetchRegistry: true

spring:
  cloud:
    config:
      server:
        prefix: configuration
  boot:
    admin:
      contextPath: /admin
      discovery:
        converter:
          managementContextPath: /manage
          
http:
  client:
    ssl:
      trust-store: truststores/truststore.jks
      trust-store-password: changeit  