server:
  port: 8761

eureka:
  server:
    enable-self-preservation: false
  instance:
    statusPageUrlPath: ${management.contextPath}/info
    healthCheckUrlPath: ${management.contextPath}/health
  client:
    register-with-eureka: true
    fetchRegistry: true 
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true    

spring:
  cloud:
    config:
      server:
        prefix: configuration
  boot:
    admin:
      contextPath: /admin
      discovery:
        converter:
          managementContextPath: /manage
          
http:
  client:
    ssl:
      trust-store: truststores/truststore.jks
      trust-store-password: changeit

turbine:
  appConfig: discovery,documents,processos,autuacao,distribuicao,peticionamento,recebimento
  instanceUrlSuffix: /manage/hystrix.stream
  clusterNameExpression: new String("default")
  combineHostPort: true