server:
  port: 8094

onlyoffice:
  server:
    address: https://docker:443
    
cassandra:
  keyspace: documents
  contactpoints: cassandra
  port: 9042
  
spring:
  datasource:
    url: jdbc:h2:mem:${spring.application.name};MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
  h2:
    console:
      enabled: true