eureka:
  instance:
    preferIpAddress: true
    
spring:
  datasource:
    url: jdbc:oracle:thin:@stfdigital:1521/poc
    username: documents
    password: 123
    initialize: false
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
onlyoffice:
  server:
    address: https://digital.stf.jus.br:9443
  integration:
    address: onlyoffice
    port: 9443
  documentserver:
    host: digital.stf.jus.br