server:
  port: 8094

management:
  contextPath: /manage

spring:
  datasource:
    url: jdbc:h2:mem:documents;MODE=Oracle;DB_CLOSE_DELAY=-1
    username: sa
    password: 
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none

eureka:  
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    healthcheck:
      enabled: true
    
flyway:
  validate-on-migrate: false

mongo:
  host: mongo
  databaseName: documento

http:
  client:
    ssl:
      trust-store: truststores/truststore.jks
      trust-store-password: changeit
onlyoffice:
  server:
    address: https://docker:443
      
security:
  oauth2:
    resource:
      user-info-uri: http://userauthentication:8095/user
      
feign:
  hystrix:
    enabled: false