server:
  port: 8765
  ssl:
    key-store: ssl/docker/server.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: docker

management:
  contextPath: /manage
   
info:
  component: Zuul Server

eureka:

  client: 
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    healthcheck:
      enabled: true      
  instance:
    preferIpAddress: false
    hostname: docker
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: ${server.port}
    statusPageUrlPath: ${management.contextPath}/info
    healthCheckUrlPath: ${management.contextPath}/health    
    
security:
  oauth2:
    resource:
      user-info-uri: http://userauthentication:8095/user
    
zuul:
  sensitive-headers: 
  routes:
    discovery:
      url: http://discovery:8761

# Aumentando o timeout do gateway
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
  
  