eureka:
  instance:
    preferIpAddress: true
    
spring:
  datasource:
    url: jdbc:oracle:thin:@stfdigital:1521/poc
    username: recebimento
    password: 123
    initialize: false
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect