server:
  port: 8081
  
management:
  contextPath: /manage

spring:
  datasource:
    url: jdbc:h2:mem:services;MODE=Oracle;DB_CLOSE_DELAY=-1
    username: sa
    password: 
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none

eureka:
  instance:
    statusPageUrlPath: ${management.contextPath}/info
    healthCheckUrlPath: ${management.contextPath}/health
  client:  
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    healthcheck:
      enabled: true
    
flyway:
  validate-on-migrate: false

http:
  client:
    ssl:
      trust-store: truststores/truststore.jks
      trust-store-password: changeit      
      
security:
  oauth2:
    resource:
      user-info-uri: http://userauthentication:8095/user
      
hystrix.command.default.execution.isolation.strategy: SEMAPHORE