server:
  port: 8095

management:
  contextPath: /manage

spring:
  datasource:
    url: jdbc:h2:mem:userauthentication;MODE=Oracle;DB_CLOSE_DELAY=-1
    username: sa
    password: 
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none

eureka:  
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    healthcheck:
      enabled: true
    
flyway:
  validate-on-migrate: false

http:
  client:
    ssl:
      trust-store: truststores/truststore.jks
      trust-store-password: changeit
