server:
  port: 8761
  
spring:
  application:
    name: discovery

eureka:
  server:
    enable-self-preservation: false
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: false
    fetchRegistry: false
    healthcheck:
      enabled: true
           
http:
  client:
    ssl:
      trust-store: truststores/truststore.jks
      trust-store-password: changeit
      
security:
  oauth2:
    client:
      clientId: peticionamento
      clientSecret: peticionamento
      accessTokenUri: http://userauthentication:8095/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://userauthentication:8095/user
      