server:
  port: 8761
  
spring:
  application:
    name: discovery
  datasource:
    url: jdbc:h2:mem:discovery;MODE=Oracle;DB_CLOSE_DELAY=-1
    username: sa
    password: 
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none

eureka:
  server:
    enable-self-preservation: false
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: false
    fetchRegistry: false
    healthcheck:
      enabled: true

flyway:
  validate-on-migrate: false

http:
  client:
    ssl:
      trust-store: truststores/truststore.jks
      trust-store-password: changeit
      
security:
  oauth2:
    resource:
      user-info-uri: http://userauthentication:8095/user
